# tested in github actions using this
# [action](https://github.com/jgibbons-cp/datadog/blob/full_cicd_knote/.github/workflows/docker_build.yaml)
FROM node:18.0-slim
COPY . .
RUN npm install dd-trace --save
# install tracer - using this command i was able to reproduce
# Error: Cannot find module 'dd-trace/init' on github actions
#CMD  ["npm", "install", "dd-trace --save"]
# using RUN it successfully built and deployed on github actions
#RUN npm install dd-trace --save
# talk to local Datadog agent service - this is probably it
# see readme on how to find it
ENV DD_AGENT_HOST="datadog-agent"
# Datadog correlation tags - examples
# meaningful to you - service instrumented, version for deployment tracking
# env for grouping dev, prod, dev_description etc.
ENV DD_SERVICE="knote"
ENV DD_VERSION="1"
ENV DD_ENV="lab"
# Datadog code profiling
ENV DD_PROFILING_ENABLED="true"
# Datadog runtime metrics
ENV DD_RUNTIME_METRICS_ENABLED="true"
# without Datadog library
CMD node index.js
# with Datadog library
#CMD node --require dd-trace/init index.js
