## tested in github actions using this
# https://github.com/jgibbons-cp/datadog/blob/full_cicd_knote/.github/workflows/docker_build.yaml
FROM debian:bullseye-slim
ENV NODE_VERSION 19.8.1
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
RUN node --version
RUN npm --version
COPY . .
#
# install tracer - using this command i was able to reproduce
# Error: Cannot find module 'dd-trace/init' on github actions
#CMD  ["npm", "install", "dd-trace --save"]
# using RUN it successfully built on github actions and deployed to k8s
#
# no dd
#RUN npm install -g n;n latest
#RUN npm install -g npm@19.8.1
#RUN npm install
#
# with dd
#
#RUN npm install dd-trace --save
#
# talk to local Datadog agent service - this is probably it
# see readme on how to find it
#
# only works in the same namespace
# ENV DD_AGENT_HOST="datadog-agent"
#
# fully qualified dns to a names namespace datadog
#ENV DD_AGENT_HOST="datadog-agent.datadog.svc.cluster.local"
#
# Datadog correlation tags - examples
# meaningful to you - service instrumented, version for deployment tracking
# env for grouping dev, prod, dev_description etc.
#
#ENV DD_SERVICE=""
#ENV DD_VERSION=""
#ENV DD_ENV=""
#
# Datadog code profiling
#ENV DD_PROFILING_ENABLED="true"
#
# Datadog runtime metrics
#
#ENV DD_RUNTIME_METRICS_ENABLED="true"
#
# debug logs
#
#ENV DD_TRACE_DEBUG="true"
#ENV DD_TRACE_STARTUP_LOGS="true"
#
# without Datadog library
CMD node index.js
# with Datadog library
#
#CMD node --require dd-trace/init index.js
