FROM tomcat:9.0
LABEL maintainer=”jenks.gibbons@datadoghq.com”
LABEL "com.datadoghq.ad.logs"='[{"source":"tomcat","service":"tomcat","log_processing_rules":[{"type":"multi_line","name":"log_start_with_date","pattern":"\\d{4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"}]}]'
ADD /target/app-java-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/
ADD  ./dd-java-agent.jar /usr/local/tomcat/lib/
EXPOSE 8080
