FROM tomcat:9.0-jdk8-corretto-al2
LABEL maintainer=”jenks.gibbons@datadoghq.com”
ADD /target/app-java-0.0.1-SNAPSHOT.war /usr/local/tomcat/webapps/
ARG TRACER
ENV env_TRACER $TRACER
ADD  ./$TRACER /usr/local/tomcat/lib/
EXPOSE 8080
CMD ["/usr/local/tomcat/bin/catalina.sh", "run"]
