name: snyk-vulnerability-assessment
#on: push
on: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '00 10 * * 1'
env:
    SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
    DATADOG_APP_KEY: ${{ secrets.DATADOG_APP_KEY }}
    JAVA_HOME: /usr/local/openjdk-11 # Covers a bug in building this version of struts from this version of JDK
jobs:
    vulnerability_analysis:
      runs-on: ubuntu-latest
      defaults:
        run:
          shell: bash
          working-directory: /home/runner/work/datadog/datadog/
      steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
            java-version: 11.0.4
            java-package: jdk
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install Datadog CI
        run: npm install -g --save-dev @datadog/datadog-ci
        shell: bash
      - name: Build artifacts with Maven
        run: cd app-java && mvn install # Artifacts must be pre-built in order to generate the dependency graph
        shell: bash
        continue-on-error: true
      - name: test
        run: ls -l /home/runner/work/datadog/datadog/
      - uses: datadog/github-action-vulnerability-analysis@master
        with:
          #build-file: 'pom.xml'
          service: 'java-app'
          version: '.01' # Must align with the version in the CDK for everything to match up
          #datadog-api-key: ${{ secrets.DD_API_KEY }}
          #datadog-app-key: ${{ secrets.DD_APP_KEY }}
          #snyk-token: ${{ secrets.SNYK_TOKEN }}
